import "./styles.css";
import image1 from "./assets/images/image-1.svg";
import image2 from "./assets/images/image-2.svg";
import image3 from "./assets/images/image-3.svg";
import image4 from "./assets/images/image-4.svg";
import image5 from "./assets/images/image-5.svg";
import image6 from "./assets/images/image-6.svg";
import image7 from "./assets/images/image-7.svg";
import image8 from "./assets/images/image-8.svg";
import image9 from "./assets/images/image-9.svg";
import image10 from "./assets/images/image-10.svg";
import image11 from "./assets/images/image-11.svg";
import image12 from "./assets/images/image-12.svg";
import image13 from "./assets/images/image-13.svg";
import icon1 from "./assets/icons/icon-1.svg";
import icon2 from "./assets/icons/icon-2.svg";
import headerBackground from "./assets/images/header-background.svg";

document.getElementById("image-2").setAttribute("src", image2);
document.getElementById("image-3").setAttribute("src", image3);
document.getElementById("image-4").setAttribute("src", image4);
document.getElementById("image-5").setAttribute("src", image5);
document.getElementById("image-6").setAttribute("src", image6);
document.getElementById("image-7").setAttribute("src", image7);
document.getElementById("image-8").setAttribute("src", image8);
document.getElementById("image-9").setAttribute("src", image9);
document.getElementById("image-10").setAttribute("src", image10);
document.getElementById("image-11").setAttribute("src", image11);
document.getElementById("image-12").setAttribute("src", image12);
document.getElementById("image-13").setAttribute("src", image13);
document.getElementById("icon-1").setAttribute("src", icon1);
document.getElementById("icon-2").setAttribute("src", icon2);
document.getElementById("icon-3").setAttribute("src", icon1);
document.getElementById("icon-4").setAttribute("src", icon2);
